# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file

name: 'Terragrunt Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select an environment to continue
        options: 
        - dev
        - int
        - staging
        - prod
permissions:
  contents: read

jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Install the latest version of Terragrunt CLI and configure the Terragrunt CLI configuration 
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.45.5
    
    - name: Check Versions
      run: |
        terragrunt --version
        terraform --version
        pwd
        ls -lrta
    
    - name: Set arguments
      run: |
        export TERRAGRUNT_LOG_LEVEL=debug
        echo ${{ github.event.inputs.environment }}"
        export ARM_CLIENT_ID=${{secrets.ARM_CLIENT_ID}}
        export ARM_CLIENT_SECRET=${{secrets.ARM_CLIENT_SECRET}}
        export ARM_TENANT_ID=${{secrets.ARM_TENANT_ID}}
        export ARM_SUBSCRIPTION_ID=${{secrets.ARM_SUBSCRIPTION_ID}}

    
    - name: Terragrunt Init
      run: |
        terragrunt init --terragrunt-working-dir ${{ github.event.inputs.environment }}"
        
      
     
